name: add_to_wallet
description: Flutter plugin exposing native PKAddPassButton to interact with the Apple Wallet
version: 0.0.2
homepage: https://github.com/barkibu/add_to_wallet
repository: https://github.com/barkibu/add_to_wallet

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.barkibu.add_to_wallet
        pluginClass: AddToWalletPlugin
      ios:
        pluginClass: AddToWalletPlugin
